data:
    base:
      name: TP_RJ
      bin_sz: .01
      lag: .1
    segments:
      dur: .2
      radcurv_bounds: [.2, 5]
    pairing:
      proc_kind: affine
      dist: proc_dist
      same_pctl: .1
      notSame_pctl: .2
      exclude_pctl: .8
    sameness:
      flat_neural_bin_sz__grid: [.05, .02]
      triplet_min_prevalence: 5

model:
  dim__grid: [5, 4]
  dropout__grid: [.5, .75]

training:
  cv:
    folds: 3
  progress_mgr_params:
    patience: .1
    overfit: 0.15
    converge: 1.e-4
  epochs: 100
  batch_size: 64
  epoch_size_factor: .25
  loss_margin: 1.0
  optim_params:
    kind__grid: [SGD, Adam]
    lr__grid: [1.e-3, 1.e-4, 1.e-2]
