data:
    base:
      name: TP_RJ
      bin_sz: .01
      lag: .1
    segments:
      dur: .2
      radcurv_bounds: [.2, 5]
    pairing:
      proc_kind: affine
      dist: proc_dist
      same_pctl: .1
      notSame_pctl: .2
      exclude_pctl: .8
    sameness:
      flat_neural_bin_sz: .05
      triplet_min_prevalence: 5
      normalize_neural: True

model:
  dim: 3
  dropout: 0.75

training:
  cv:
    folds: 3
  progress_mgr_params:
    patience: null
    overfit: 100
    converge: 1.e-4
  epochs: 100
  batch_size: 32
  epoch_size_factor: .25
  loss_margin: 1.0
  optim_params:
    kind: Adam
    lr: 5.e-05
