data:
    base:
      name: TP_RS
      bin_sz: .01
      lag: .1
    segments:
      dur: .2
      radcurv_bounds: [[.2, 5]]
    pairing:
      variable: kin.EuSpd
      metric: [rigid]
      same_pctl: .05
      notSame_pctl: .2
      exclude_pctl: .8
      max_pairs: 100000
      balance: [True]
    predictor:
      variable: neural
      bin_sz: [.05]
      normalize: True
      triplet_min_prevalence: 5
      shuffle: False

model:
  dim: [3, 7]
  dropout: [0.5]

training:
  cv:
    rand_seed: 0
    folds: 3
  progress_mgr_params:
    patience: null
    overfit: 100
    converge: 1.e-4
  epochs: 100
  batch_size: [32]
  batches_in_epoch: 2000
  loss_margin: [1.0]
  optim_params:
    kind: [SGD]
    lr: [5.e-03, 1.e-03, 1.e-04]
