data:
    trials:
      name: TP_RS
      bin_sz: .05
      lag: .1
    segments:
      dur: .2
      radcurv_bounds: [[.2, 5]]
    pairing:
      variable: kin.EuSpd
      align_kind: [none]
      dist_metric: [absavg]
      same_pctl: .05
      notSame_pctl: .2
      exclude_pctl: .8
      max_pairs: 100000
      balance: [True]
      shuffle: False
    inputs:
      variable: neural
      bin_sz: [.02]
      drop_zero_variance: True
      normalize: True

model:
  dim: [3, 7]
  dropout: [0.5]

training:
  cv:
    rand_seed: 0
    folds: 3
  progress_mgr_params:
    patience: null
    overfit: 100
    converge: 1.e-4
  p_hard: .5
  epochs: 100
  batch_size: [64]
  batches_in_epoch: 4000
  n_eval_triplets: 5000
  loss_margin: [1.0]
  optim_params:
    kind: [SGD]
    lr: [5.e-04, 1.e-03, 1.e-04]
