data:
    base:
      name: TP_RJ
      bin_sz: .01
      lag: .1
    segments:
      dur: .2
      radcurv_bounds: [.2, 5]
    pairing:
      proc_kind: affine
      dist: proc_dist
      same_pctl: .1
      notSame_pctl: .2
      exclude_pctl: .8
    sameness:
      flat_neural_bin_sz: .05
      triplet_min_prevalence: 5

model_selection:
  score: acc
  rand_seed: 0
  folds: 5
  train_split: .8

embedding:
    model:
      dim: 5
      dropout: .5
    training:
      epochs: 1000
      batch_size: 64
      loss_margin: 1.0
      optim_params:
        kind: Adam
        lr: 5e-5
